# Generated by Django 3.2.5 on 2021-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='image',
            field=models.ImageField(default='author-3.jpg', upload_to='comment'),
        ),
    ]
